server:
  port: 8080  #端口
spring:
  application:
    name: api-gateway-server
#配置springCloudGateway的路由
  cloud:
    gateway:
      routes:
      #配置路由：路由ID，路由到微服务的URL，断言（判断条件）
        - id: product-service #随便起
          #uri: http://127.0.0.1:9001
          uri: lb://service-product #uri : uri以 lb: //开头(lb代表从注册中心获取服务)，后面接的就是你需要转发到的服务名称
          predicates: #断言 配置路由条件:
            #- Path=/product/** #路径匹配规则，路径中有product就会根据这个规则来
            - Path=/product-service/** #将请求转发到 http://localhost:9001/product/1
          filters: #配置路由过滤器
            - RewritePath=/product-service/(?<segment>.*), /$\{segment} # http://localhost:8080/product-service/product/1 --》 http://localhost:9001/product/1
      #配置自动的根据服务名称惊醒路由转发 http://localhost:8080/服务名/product/1
      discovery:
        locator:
          enabled: true #开启根据服务名称自动转发
          lower-case-service-id: true #微服务名称已小写形式呈现
eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true #使用ip注册