server:
  port: 9002 #服务端口
spring:
  application:
    name: service-order #服务名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud——test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345678
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true