server:
  port: 7002 #服务端口
spring:
  application:
    name: stream_consumer #指定服务名
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
  cloud:
    stream:
      instanceCount: 2  #消费者数量
      instanceIndex: 0  #消费者索引 从0开始
      bindings:
        input:  #内置的获取消息的通道 从itcast-default中获取
          destination: itcast-default
        myinput:
          destination: custom-output
          group: group1
          consumer:
            partitioned: true
      binders:
        defaultRabbit:
          type: rabbit